// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZonWiki.Infrastructure.Persistence;

#nullable disable

namespace ZonWiki.Infrastructure.Migrations
{
    [DbContext(typeof(ZonWikiDbContext))]
    [Migration("20260415074538_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonWiki.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Article_Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("Article_CategoryId");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Article_ContentHash");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Article_ContentHtml");

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Article_ContentRaw");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Article_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Article_CreatedUser");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Article_FilePath");

                    b.Property<bool>("PublishedFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Article_PublishedFlag");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Article_Slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Article_Title");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Article_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Article_UpdatedUser");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Article_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Article");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Article_CategoryId");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("UX_Article_FilePath");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Article_Slug");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Category_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Category_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Category_CreatedUser");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Category_FolderPath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Category_Name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("Category_ParentId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Category_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Category_UpdatedUser");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Category_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Category");

                    b.HasIndex("FolderPath")
                        .IsUnique()
                        .HasDatabaseName("UX_Category_FolderPath");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Category_ParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_Id");

                    b.Property<string>("AnchorData")
                        .HasColumnType("jsonb")
                        .HasColumnName("Comment_AnchorData");

                    b.Property<string>("AnchorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Comment_AnchorType");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_ArticleId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comment_Content");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Comment_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Comment_CreatedUser");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Comment_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Comment_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Comment_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Comment");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("IX_Comment_ArticleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Comment_UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("User_Id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("User_AvatarUrl");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("User_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("User_CreatedUser");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("User_Email");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_GoogleSub");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("User_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("User_UpdatedUser");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("User_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("UX_User_GoogleSub");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Article", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Article_Category_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Category_Category_ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Article_ArticleId");

                    b.HasOne("ZonWiki.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_User_UserId");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
