// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZonWiki.Infrastructure.Persistence;

#nullable disable

namespace ZonWiki.Infrastructure.Migrations
{
    [DbContext(typeof(ZonWikiDbContext))]
    [Migration("20260611025420_UserScopedSchemaRedesign")]
    partial class UserScopedSchemaRedesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonWiki.Domain.Entities.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AiModel_Id");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("AiModel_ApiKeyEncrypted");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("AiModel_BaseUrl");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AiModel_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("AiModel_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AiModel_DeletedDateTime");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("AiModel_Enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("AiModel_Key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("AiModel_Kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("AiModel_Label");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("AiModel_ModelId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("AiModel_Notes");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("AiModel_Provider");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("AiModel_TimeoutSeconds");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AiModel_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("AiModel_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("AiModel_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("AiModel_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_AiModel");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_AiModel_UserId_Key");

                    b.ToTable("AiModel");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.CaptureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CaptureItem_Id");

                    b.Property<string>("AudioPath")
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_AudioPath");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CaptureItem_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CaptureItem_DeletedDateTime");

                    b.Property<Guid?>("FiledTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("CaptureItem_FiledTargetId");

                    b.Property<string>("FiledTargetType")
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_FiledTargetType");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_RawContent");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_Source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_Status");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CaptureItem_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CaptureItem_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("CaptureItem_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("CaptureItem_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_CaptureItem");

                    b.ToTable("CaptureItem");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Category_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Category_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Category_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Category_DeletedDateTime");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Category_FolderPath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Category_Name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("Category_ParentId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Category_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Category_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Category_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Category_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Category_ParentId");

                    b.HasIndex("UserId", "FolderPath")
                        .HasDatabaseName("IX_Category_UserId_FolderPath");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_Id");

                    b.Property<string>("AnchorData")
                        .HasColumnType("jsonb")
                        .HasColumnName("Comment_AnchorData");

                    b.Property<string>("AnchorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Comment_AnchorType");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Comment_Content");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Comment_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Comment_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Comment_DeletedDateTime");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_NoteId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Comment_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Comment_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Comment_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Comment_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Comment");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("IX_Comment_NoteId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Comment_UserId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Note_Id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Note_ContentHash");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Note_ContentHtml");

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Note_ContentRaw");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Note_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Note_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Note_DeletedDateTime");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("Note_IsDraft");

                    b.Property<DateTime?>("JournalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Note_JournalDate");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Note_Kind");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Note_Slug");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Note_SourceFilePath");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Note_Title");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Note_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Note_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Note_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Note_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Note");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Note_UserId_Slug");

                    b.HasIndex("UserId", "SourceFilePath")
                        .HasDatabaseName("IX_Note_UserId_SourceFilePath");

                    b.HasIndex("UserId", "Kind", "JournalDate")
                        .HasDatabaseName("IX_Note_UserId_Kind_JournalDate");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NoteCategory_Id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteCategory_CategoryId");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteCategory_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteCategory_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteCategory_DeletedDateTime");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteCategory_NoteId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteCategory_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteCategory_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteCategory_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("NoteCategory_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_NoteCategory");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_NoteCategory_CategoryId");

                    b.HasIndex("NoteId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_NoteCategory_NoteId_CategoryId");

                    b.ToTable("NoteCategory");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NoteLink_Id");

                    b.Property<string>("AnchorText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NoteLink_AnchorText");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteLink_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteLink_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteLink_DeletedDateTime");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteLink_SourceNoteId");

                    b.Property<Guid?>("TargetNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteLink_TargetNoteId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteLink_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteLink_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteLink_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("NoteLink_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_NoteLink");

                    b.HasIndex("SourceNoteId")
                        .HasDatabaseName("IX_NoteLink_SourceNoteId");

                    b.HasIndex("TargetNoteId")
                        .HasDatabaseName("IX_NoteLink_TargetNoteId");

                    b.HasIndex("UserId", "SourceNoteId")
                        .HasDatabaseName("IX_NoteLink_UserId_SourceNoteId");

                    b.ToTable("NoteLink");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NoteRevision_Id");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("NoteRevision_ChangeKind");

                    b.Property<string>("ContentRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteRevision_ContentRaw");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteRevision_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteRevision_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteRevision_DeletedDateTime");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteRevision_NoteId");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer")
                        .HasColumnName("NoteRevision_RevisionNo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NoteRevision_Title");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteRevision_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteRevision_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteRevision_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("NoteRevision_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_NoteRevision");

                    b.HasIndex("NoteId", "RevisionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_NoteRevision_NoteId_RevisionNo");

                    b.ToTable("NoteRevision");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTag_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTag_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteTag_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTag_DeletedDateTime");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTag_NoteId");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTag_TagId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTag_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteTag_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTag_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("NoteTag_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_NoteTag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_NoteTag_TagId");

                    b.HasIndex("NoteId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("UX_NoteTag_NoteId_TagId");

                    b.ToTable("NoteTag");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteTaskLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTaskLink_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTaskLink_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteTaskLink_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTaskLink_DeletedDateTime");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTaskLink_NoteId");

                    b.Property<Guid>("TaskCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTaskLink_TaskCardId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NoteTaskLink_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NoteTaskLink_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("NoteTaskLink_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("NoteTaskLink_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_NoteTaskLink");

                    b.HasIndex("TaskCardId")
                        .HasDatabaseName("IX_NoteTaskLink_TaskCardId");

                    b.HasIndex("NoteId", "TaskCardId")
                        .IsUnique()
                        .HasDatabaseName("UX_NoteTaskLink_NoteId_TaskCardId");

                    b.ToTable("NoteTaskLink");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.QuickLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("QuickLink_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("QuickLink_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QuickLink_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("QuickLink_DeletedDateTime");

                    b.Property<string>("IconKey")
                        .HasColumnType("text")
                        .HasColumnName("QuickLink_IconKey");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("QuickLink_SortOrder");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QuickLink_Title");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("QuickLink_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QuickLink_UpdatedUser");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QuickLink_Url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("QuickLink_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("QuickLink_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_QuickLink");

                    b.ToTable("QuickLink");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Tag_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Tag_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Tag_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Tag_DeletedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Tag_Name");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Tag_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("Tag_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Tag_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Tag_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_Tag");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Tag_UserId_Name");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TaskCard_Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaskCard_Content");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskCard_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TaskCard_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskCard_DeletedDateTime");

                    b.Property<DateTime?>("DueDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskCard_DueDateTime");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskCard_GroupId");

                    b.Property<DateTime?>("PlannedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskCard_PlannedDateTime");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("TaskCard_Priority");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("text")
                        .HasColumnName("TaskCard_RecurrenceRule");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("TaskCard_SortOrder");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("TaskCard_Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TaskCard_Title");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskCard_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TaskCard_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskCard_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("TaskCard_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_TaskCard");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_TaskCard_GroupId");

                    b.HasIndex("UserId", "DueDateTime")
                        .HasDatabaseName("IX_TaskCard_UserId_DueDateTime");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_TaskCard_UserId_Status");

                    b.ToTable("TaskCard");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TaskGroup_Id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("TaskGroup_Color");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskGroup_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaskGroup_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskGroup_DeletedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaskGroup_Name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("TaskGroup_SortOrder");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskGroup_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TaskGroup_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskGroup_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("TaskGroup_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_TaskGroup");

                    b.ToTable("TaskGroup");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("TaskRelation_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskRelation_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TaskRelation_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskRelation_DeletedDateTime");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("TaskRelation_Kind");

                    b.Property<Guid>("SourceTaskCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskRelation_SourceTaskCardId");

                    b.Property<Guid>("TargetTaskCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskRelation_TargetTaskCardId");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("TaskRelation_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TaskRelation_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("TaskRelation_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("TaskRelation_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_TaskRelation");

                    b.HasIndex("TargetTaskCardId")
                        .HasDatabaseName("IX_TaskRelation_TargetTaskCardId");

                    b.HasIndex("SourceTaskCardId", "TargetTaskCardId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_TaskRelation_SourceTaskCardId_TargetTaskCardId_Kind");

                    b.ToTable("TaskRelation");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("User_Id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("User_AvatarUrl");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("User_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("User_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("User_DeletedDateTime");

                    b.Property<string>("DisplayMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("User_DisplayMode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("User_Email");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("User_GoogleSub");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("User_TimeZone");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("User_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("User_UpdatedUser");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("User_ValidFlag");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("UX_User_GoogleSub");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Whiteboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Whiteboard_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Whiteboard_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Whiteboard_CreatedUser");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Whiteboard_DeletedDateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Whiteboard_Name");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("Whiteboard_NoteId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("Whiteboard_SortOrder");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Whiteboard_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Whiteboard_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("Whiteboard_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("Whiteboard_ValidFlag");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("Whiteboard_X");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("Whiteboard_Y");

                    b.HasKey("Id")
                        .HasName("PK_Whiteboard");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("IX_Whiteboard_NoteId");

                    b.HasIndex("UserId", "NoteId")
                        .HasDatabaseName("IX_Whiteboard_UserId_NoteId");

                    b.ToTable("Whiteboard");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.WhiteboardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("WhiteboardItem_Id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("WhiteboardItem_CreatedDateTime");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("WhiteboardItem_CreatedUser");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("WhiteboardItem_DataJson");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("WhiteboardItem_DeletedDateTime");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("WhiteboardItem_Height");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("WhiteboardItem_Kind");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("WhiteboardItem_UpdatedDateTime");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("WhiteboardItem_UpdatedUser");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("WhiteboardItem_UserId");

                    b.Property<bool>("ValidFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("WhiteboardItem_ValidFlag");

                    b.Property<Guid>("WhiteboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("WhiteboardItem_WhiteboardId");

                    b.Property<double?>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("WhiteboardItem_Width");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("WhiteboardItem_X");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("WhiteboardItem_Y");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("WhiteboardItem_ZIndex");

                    b.HasKey("Id")
                        .HasName("PK_WhiteboardItem");

                    b.HasIndex("WhiteboardId")
                        .HasDatabaseName("IX_WhiteboardItem_WhiteboardId");

                    b.ToTable("WhiteboardItem");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Category_Category_ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany("Comments")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Note_NoteId");

                    b.HasOne("ZonWiki.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_User_UserId");

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteCategory", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Category", "Category")
                        .WithMany("NoteCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NoteCategory_Category_CategoryId");

                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany("NoteCategories")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NoteCategory_Note_NoteId");

                    b.Navigation("Category");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteLink", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "SourceNote")
                        .WithMany()
                        .HasForeignKey("SourceNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NoteLink_Note_SourceNoteId");

                    b.HasOne("ZonWiki.Domain.Entities.Note", "TargetNote")
                        .WithMany()
                        .HasForeignKey("TargetNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_NoteLink_Note_TargetNoteId");

                    b.Navigation("SourceNote");

                    b.Navigation("TargetNote");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteRevision", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NoteRevision_Note_NoteId");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NoteTag_Note_NoteId");

                    b.HasOne("ZonWiki.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NoteTag_Tag_TagId");

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.NoteTaskLink", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NoteTaskLink_Note_NoteId");

                    b.HasOne("ZonWiki.Domain.Entities.TaskCard", "TaskCard")
                        .WithMany()
                        .HasForeignKey("TaskCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NoteTaskLink_TaskCard_TaskCardId");

                    b.Navigation("Note");

                    b.Navigation("TaskCard");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskCard", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.TaskGroup", "Group")
                        .WithMany("TaskCards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TaskCard_TaskGroup_GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskRelation", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.TaskCard", "SourceTaskCard")
                        .WithMany()
                        .HasForeignKey("SourceTaskCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TaskRelation_TaskCard_SourceTaskCardId");

                    b.HasOne("ZonWiki.Domain.Entities.TaskCard", "TargetTaskCard")
                        .WithMany()
                        .HasForeignKey("TargetTaskCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TaskRelation_TaskCard_TargetTaskCardId");

                    b.Navigation("SourceTaskCard");

                    b.Navigation("TargetTaskCard");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Whiteboard", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Whiteboard_Note_NoteId");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.WhiteboardItem", b =>
                {
                    b.HasOne("ZonWiki.Domain.Entities.Whiteboard", "Whiteboard")
                        .WithMany("Items")
                        .HasForeignKey("WhiteboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WhiteboardItem_Whiteboard_WhiteboardId");

                    b.Navigation("Whiteboard");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("NoteCategories");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Note", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("NoteCategories");

                    b.Navigation("NoteTags");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.TaskGroup", b =>
                {
                    b.Navigation("TaskCards");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ZonWiki.Domain.Entities.Whiteboard", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
